### ISSUE TITLE
Missing event loop

### ISSUE THREAD

**Issue by ofosos** [PrefectHQ/prefect-jupyter#19]
Heya,
I'm getting a problem when executing Jupyter Notebooks in my Prefect setup:

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/prefect/engine.py", line 1488, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/prefect_jupyter/notebook.py", line 77, in execute_notebook
    return pm.execute_notebook(
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/papermill/execute.py", line 113, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/papermill/engines.py", line 367, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/papermill/engines.py", line 436, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/papermill/clientwrap.py", line 46, in execute
    info_msg = self.wait_for_reply(self.kc.kernel_info())
  File "/home/user/.local/share/virtualenvs/prefect-TsbxTCQL/lib/python3.10/site-packages/jupyter_client/asynchronous/client.py", line 20, in _
    fut: asyncio.Future = asyncio.Future()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.
05:32:34 AM
execute_notebook-a4378ab6-0

Finished in state Failed("Task run encountered an exception: RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.\n")
```

**Comment by ofosos** [comment]
Just a note: the Notebook completes successfully, but somewhere the task raises an error.
